title: Srinivas Kumar's point of "TECH a Look"
description: If you are Techie like me, you shall find this blog posts useful to you. You shall find Useful Articles, Programming Language Tips and Tricks, Code Snippets, Knowledge Base, My Personal Experiences and some fun stuff. Happy Reading
baseurl: "https://www.srinivasakumar.com" # the subpath of your site, e.g. /blog
url: "https://www.srinivasakumar.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Srinivas Kumar
author-image:   1.jpg
author-job:     Entrepreneur, Programmer, Maverick
author-email:   srinivasakumar.a@gmail.com # Add your email for contant form.
author-twitter: ASrinivasaKumar # Add your twitter account
about-author:   I'm an Entrepreneur, SAP ERP Programmer, Marketing and Photography skills.

# Social settings
social-twitter:   ASrinivasaKumar
social-facebook:  sriniak
social-github:    srinivasakumar-a
social-pinterest:
social-instagram:
social-youtube:   UCRum6O_-XEkQgqvukltVeBQ
social-vk:
social-linkedin:  sriniak

# Newsletter
mailchimp: sriniak # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: UA-161904857-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: pragna # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
